name: Install dependencies with updated pip

on: [push]  # Se déclenche à chaque "git push"

jobs:
  install-and-deploy:
    runs-on: ubuntu-latest  # Laissez ubuntu-latest, c'est optimal pour GitHub

    steps:
      # Étape 1 - Récupère le code
      - uses: actions/checkout@v4

      # Étape 2 - Configure Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Version de Python (modifiable)

      # Étape 3 - Met à jour pip SILENCIEUSEMENT (supprime les warnings)
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip --quiet
          pip config set global.no-warn-script-location true

      # Étape 4 - Installe les dépendances
      - name: Install dependencies
        run: pip install -r requirements.txt
